// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu17FNlWG_2uYBW3wz0-NZs2tYtR-dcn0',
    appId: '1:1034095271859:android:626913494aac4c0b70f5c6',
    messagingSenderId: '1034095271859',
    projectId: 'ifitchallenge-b8c27',
    storageBucket: 'ifitchallenge-b8c27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5vYf-GktG1_F-ewIFBdm42O50kbys-8',
    appId: '1:1034095271859:ios:714d4079d1ec036470f5c6',
    messagingSenderId: '1034095271859',
    projectId: 'ifitchallenge-b8c27',
    storageBucket: 'ifitchallenge-b8c27.appspot.com',
    androidClientId: '1034095271859-jajbrosqakrttj0uq2a38dgmaclna6nm.apps.googleusercontent.com',
    iosClientId: '1034095271859-g71ppn2095e9feev9jub7bdmppc598t2.apps.googleusercontent.com',
    iosBundleId: 'com.appevolvelabs.ifitchallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR5vYf-GktG1_F-ewIFBdm42O50kbys-8',
    appId: '1:1034095271859:ios:bfc50aec616f36fd70f5c6',
    messagingSenderId: '1034095271859',
    projectId: 'ifitchallenge-b8c27',
    storageBucket: 'ifitchallenge-b8c27.appspot.com',
    androidClientId: '1034095271859-jajbrosqakrttj0uq2a38dgmaclna6nm.apps.googleusercontent.com',
    iosClientId: '1034095271859-pa0p1o5fk6br93uf89r9gcd62j1671ds.apps.googleusercontent.com',
    iosBundleId: 'com.appevolvelabs.ifitchallenge.RunnerTests',
  );
}
